### ISSUE TITLE
Node fails on start up

### ISSUE THREAD

**Issue by vilhjalmur89** [PX4/uvc_ros_driver#23]
Node either fails to open a port or stops after printing 'retry start streaming...'.

It often works after a few tries, but the camera may also need to be unplugged/plugged

**Comment by simonegu** [comment]
I opened a pull request #24 for this issue.
Did it failed on both PC and ARM processor?
I did find that the product_id was missing in the `uvc_find_device`, but it shouldn't affect the running of the `uvc_start_stream` function.
I tried a few times on my PC and it worked every time. Did you compiled with gcc or clang?
